### ISSUE TITLE
Sqlalchemy 1.4.49 released

### ISSUE THREAD

**Issue by rggjan** [conda-forge/sqlalchemy-feedstock#152]
## Issue

Sqlalchemy 1.4.49 with an important bug fix for mypy was just released...

cc @xylar thanks!

**Comment by ocefpaf** [comment]
Ah. This one belongs in a maintenance branch b/c it is not the latest version. See https://pypi.org/project/SQLAlchemy/1.4.49/

I'll close the bot bump PR.

**Comment by xylar** [comment]
Thanks for trying to address this, @ocefpaf.  I've got it in #155.

@rggjan, thanks for bringing this to our attention (as with the last release)!
