### ISSUE TITLE
v1.3.3 package for win64-Py36 missing

### ISSUE THREAD

**Issue by igortg** [conda-forge/sqlalchemy-feedstock#36]
Seems that one of the packages from v1.3.3 build was not published: https://anaconda.org/conda-forge/sqlalchemy/files?version=1.3.3

To keep on with my day, I'll just move to 1.3.4. But I'd like to know if there's a possible fix for this kind of situation (just to know :smile:)

Can we create a branch from v1.3.3 tag, change the build number and open a PR?

@ocefpaf

**Comment by ocefpaf** [comment]
> Can we create a branch from v1.3.3 tag, change the build number and open a PR?

Sure. If you send the PR I'll add the branch and merge it.

**Comment by nehaljwani** [comment]
I re-triggered the failed [build+upload job](https://ci.appveyor.com/project/conda-forge/sqlalchemy-feedstock/build/job/8n6l8dg8qxlf1dbe) and now we have: https://anaconda.org/conda-forge/sqlalchemy/1.3.3/download/win-64/sqlalchemy-1.3.3-py36hfa6e2cd_0.tar.bz2

It will be available over CDN in a couple of hours.

Closing, as a separate PR is no longer needed.
